server:
  port: ${port:1212}
  contextPath: /mongo/rest
  compression: 
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript

spring:
  profiles.active: dev
---
spring:
  profiles: dev
  http:
    multipart:
      max-file-size: 2000KB
      max-request-size: 2000KB
  freemarker:
    checkTemplateLocation: false
  velocity:
    resource-loader-path: classpath:/templates/velocity
  data:
    mongodb:
      database: mschool
      username: dinesh
      password: dinesh
      host: ds163034.mlab.com
      port: 63034
  mail:
    host: zmail.kandapohe.com
    port: 026
    username: znoreply@kandapohe.com
    password: zn@rep!y@kpnew
  
---
spring:
  profiles: prod
  http:
    multipart:
      max-file-size: 2000KB
      max-request-size: 2000KB
  freemarker:
    checkTemplateLocation: false
  velocity:
    resource-loader-path: classpath:/templates/velocity
  data:
    mongodb:
      username: 
      database: 
      password: 
      host: 
      port: 26101
  mail:
    host: zmail.kandapohe.com
    port: 026
    username: znoreply@kandapohe.com
    password: zn@rep!y@kpnew